### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by shabir1** [vinhkhuc/jcrfsuite#11]
While running Standalone Appliocation it works but while i am running on cluster it shows below error:

2017-08-16 12:30:00058 ERROR org.apache.spark.executor.Executor:96 - Exception in task 2.0 in stage 8.0 (TID 12)
java.lang.UnsatisfiedLinkError: third_party.org.chokkan.crfsuite.crfsuiteJNI.swig_module_init()V
	at third_party.org.chokkan.crfsuite.crfsuiteJNI.swig_module_init(Native Method)
	at third_party.org.chokkan.crfsuite.crfsuiteJNI.<clinit>(crfsuiteJNI.java:85)
	at third_party.org.chokkan.crfsuite.ItemSequence.<init>(ItemSequence.java:39)
	at com.github.jcrfsuite.CrfTrainer.loadTrainingInstances(CrfTrainer.java:49)
	at com.github.jcrfsuite.CrfTrainer.train(CrfTrainer.java:117)
	at com.github.jcrfsuite.CrfTrainer.train(CrfTrainer.java:100)

**Comment by shabir1** [comment]
Standalone Application it is working
But while running on spark cluster it is not working
i think my app is not able to load native library
error is here: this(crfsuiteJNI.new_Item__SWIG_0(), true);
swig_module_init();
Can you please help me how i fix this problem

**Comment by shabir1** [comment]
Some guys suggests me to install crfsuite on machine but i think it is not good solution because i could't install crfsuite on every machine.

**Comment by shabir1** [comment]
i have maven project and uses 
 <dependency>
            <groupId>com.github.vinhkhuc</groupId>
            <artifactId>jcrfsuite</artifactId>
            <version>0.6.1</version>
 </dependency>

**Comment by shabir1** [comment]
public static void main(String[] args) {
        CrfTrainer.train(trainFile, modelFile);
}
dependency:
```
<dependency>
       <groupId>com.github.vinhkhuc</groupId>
      <artifactId>jcrfsuite</artifactId>
       <version>0.6.1</version>
</dependency>
```

**Comment by gembin** [comment]
Call this before train.
```java
try {
	CrfSuiteLoader.load();
} catch (Exception e) {
	throw new RuntimeException(e);
}
```
